sort_order = [
    "config", # resulting order: config, tmux, tmuxinator, zoxide
]

[default_session]
preview_command = "lsd --icon always --color always {}"

[[session]]
name = "tango"
path = "~/dev/k8s/dev-envs/tango"
preview_command = "tre -l 2 -d {}"
startup_command = "jj st"

[[session]]
name = "auth"
path = "~/dev/k8s/dev-envs/auth"
preview_command = "tre -l 2 -d {}"
startup_command = "jj st"
