sort_order = [
    "config", # resulting order: config, tmux, tmuxinator, zoxide
]

[default_session]
preview_command = "tre -l 2 -d {}"
startup_command = "jj st"

[[session]]
name = "nix"
path = "~/nixos-config/"

[[session]]
name = "tango"
path = "~/dev/k8s/dev-envs/tango"

[[session]]
name = "auth"
path = "~/dev/k8s/dev-envs/auth"

[[session]]
name = "analyst"
path = "~/dev/k8s/dev-envs/analyst"

[[session]]
name = "nipfoto"
path = "~/dev/k8s/dev-envs/nipfoto"

[[session]]
name = "cgicapps"
path = "~/dev/k8s/cgicapps"

[[session]]
name = "infra"
path = "~/dev/k8s/infra"

[[session]]
name = "nvim"
path = "~/.config/nvim"
