"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "eleloi"
email = "evallverdu@mossos.cat"

[signing]
behavior = "own"
backend = "gpg"
key = "A8A8882C5990AEB6"

[aliases]
l = [
    "log",
    "-r",
    "ancestors(@, 10) | ancestors(working_copies(), 5) | bookmarks()",
]
ltags = [
    "log",
    "-r",
    "ancestors(@, 5) | ancestors(working_copies(), 5) | bookmarks() | ancestors(tags(), 5)",
]

[ui]
default-command = "log"
pager = "delta"
diff-formatter = ":git"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c",
    "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c",
    "JJDiffConflicts!",
    "$output",
    "$base",
    "$left",
    "$right",
]
merge-tool-edits-conflict-markers = true
