
[[Snippets]]
  Description = "gpg: View gpg key descriptions"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "pass gpg/key-descriptions|bat --color=always --language=markdown"

[[Snippets]]
  Description = "gpg: list secret keys"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "gpg --list-secret-keys --keyid-format LONG"

[[Snippets]]
  Description = "gpg: make secret keys backup into pass manager"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "gpg --export-secret-keys --armor | gpg --symmetric --armor --passphrase \"<password>\" --batch|pass insert --multiline  gpg/secret-keys-backup "

[[Snippets]]
  Description = "jq example filter certain key value items, case insensitive"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "pass show bitwarden-backup.json | jq '.items|..| if(.name? and (.name | ascii_downcase | contains(\"santander\"))) then . else empty end'"

[[Snippets]]
  Description = "yay: list instaled packages details with fzf"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "yay -Qq | fzf --preview 'yay -Qil {}' --layout=reverse --bind 'enter:execute(yay -Qil {} | less)'"

[[Snippets]]
  Description = "bash register .env file variables into shell"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "export $(grep -v '^#' .env | xargs -d '\\n')"

[[Snippets]]
  Description = "Generate password as passphrase"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "xkcdpass -n 3 -d - -C capitalize"

[[Snippets]]
  Description = "Docker remove all test stuff"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "docker ps --filter 'name=.test' --format {{.Names}}|xargs -t -I % sh -c 'docker stop % && docker rm %'"

[[Snippets]]
  Description = "yay: find package containing specific filename"
  Filename = "/home/eleloi/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "yay -F <filename>"
