[[snippets]]
  description = "gpg: View gpg key descriptions"
  command = "pass gpg/key-descriptions|bat --color=always --language=markdown"
  output = ""

[[snippets]]
  description = "gpg: list secret keys"
  command = "gpg --list-secret-keys --keyid-format LONG"
  output = ""

[[snippets]]
  description = "gpg: make secret keys backup into pass manager"
  command = "gpg --export-secret-keys --armor | gpg --symmetric --armor --passphrase \"<password>\" --batch|pass insert --multiline  gpg/secret-keys-backup "
  output = ""

[[snippets]]
  description = "jq example filter certain key value items, case insensitive"
  command = "pass show bitwarden-backup.json | jq '.items|..| if(.name? and (.name | ascii_downcase | contains(\"santander\"))) then . else empty end'"
  output = ""

[[snippets]]
  description = "yay: list instaled packages details with fzf"
  command = "yay -Qq | fzf --preview 'yay -Qil {}' --layout=reverse --bind 'enter:execute(yay -Qil {} | less)'"
  output = ""
